import { NextRequest, NextResponse } from "next/server";

export async function POST(request: NextRequest) {
  try {
    const { category, topic } = await request.json();

    // Check if OpenAI API key is available
    const openaiApiKey = process.env.OPENAI_API_KEY;

    if (!openaiApiKey) {
      // Fallback to mock AI if no API key
      return generateMockJoke(category, topic);
    }

    // Use real OpenAI API
    const prompt = generatePrompt(category, topic);

    const response = await fetch("https://api.openai.com/v1/chat/completions", {
      method: "POST",
      headers: {
        Authorization: `Bearer ${openaiApiKey}`,
        "Content-Type": "application/json",
      },
      body: JSON.stringify({
        model: "gpt-3.5-turbo",
        messages: [
          {
            role: "system",
            content:
              "You are a creative joke generator. Generate short, funny, family-friendly jokes. Keep them under 100 words and make them genuinely humorous.",
          },
          {
            role: "user",
            content: prompt,
          },
        ],
        max_tokens: 150,
        temperature: 0.8,
      }),
    });

    if (!response.ok) {
      throw new Error(`OpenAI API error: ${response.status}`);
    }

    const data = await response.json();
    const aiJoke = data.choices[0]?.message?.content?.trim();

    if (!aiJoke) {
      throw new Error("No joke generated by AI");
    }

    return NextResponse.json({
      joke: aiJoke,
      category,
      topic,
    });
  } catch (error) {
    console.error("Error generating joke:", error);
    // Fallback to mock AI if real AI fails
    return generateMockJoke(category, topic);
  }
}

function generatePrompt(category: string, topic: string): string {
  const categoryPrompts = {
    people: `Generate a funny, personalized joke about a person named "${topic}". Make it about their personality, job, or characteristics. Keep it light-hearted and family-friendly.`,
    animals: `Generate a funny joke about ${topic}. Make it creative and entertaining.`,
    food: `Generate a funny joke about ${topic}. Make it about food, cooking, or eating.`,
    science: `Generate a funny science or technology joke about ${topic}. Make it clever and educational.`,
    school: `Generate a funny joke about school, education, or learning related to ${topic}.`,
    work: `Generate a funny workplace joke about ${topic}. Keep it professional but humorous.`,
    health: `Generate a funny joke about health, medicine, or doctors related to ${topic}.`,
    sports: `Generate a funny sports joke about ${topic}.`,
    travel: `Generate a funny travel joke about ${topic}.`,
    music: `Generate a funny music joke about ${topic}.`,
    weather: `Generate a funny weather or nature joke about ${topic}.`,
    money: `Generate a funny joke about money, finance, or business related to ${topic}.`,
    relationships: `Generate a funny relationship joke about ${topic}. Keep it clean and family-friendly.`,
    language: `Generate a funny wordplay or language joke about ${topic}.`,
    time: `Generate a funny joke about time, calendars, or schedules related to ${topic}.`,
    general: `Generate a funny, creative joke about ${topic}. Make it entertaining and original.`,
  };

  return (
    categoryPrompts[category as keyof typeof categoryPrompts] ||
    categoryPrompts.general
  );
}

function generateMockJoke(category: string, topic: string) {
  const mockAIJokes = {
    people: [
      `Why did ${topic.split(",")[0]} go to the doctor? Because they needed a check-up!`,
      `What do you call ${topic.split(",")[0]}? A real character!`,
      `Why did ${topic.split(",")[0]} cross the road? To get to the punchline!`,
    ],
    animals: [
      `Why did the ${topic} go to the doctor? Because it was feeling a bit under the weather!`,
      `What do you call a ${topic} that sings? A musical ${topic}!`,
      `Why did the ${topic} join a band? Because it had the talent!`,
    ],
    food: [
      `Why did the ${topic} go to the party? Because it was the life of the dish!`,
      `What do you call a ${topic} that's always late? A procrastinating ${topic}!`,
      `Why did the ${topic} go to school? To get smarter!`,
    ],
    science: [
      `Why did the ${topic} go to space? Because it wanted to explore the universe!`,
      `What do you call a ${topic} that's always learning? A curious ${topic}!`,
      `Why did the ${topic} become a scientist? Because it loved experiments!`,
    ],
    general: [
      `Why did the ${topic} go on vacation? Because it needed a break!`,
      `What do you call a ${topic} that's always happy? A cheerful ${topic}!`,
      `Why did the ${topic} go to the gym? To get stronger!`,
    ],
  };

  const categoryJokes =
    mockAIJokes[category as keyof typeof mockAIJokes] || mockAIJokes.general;
  const randomJoke =
    categoryJokes[Math.floor(Math.random() * categoryJokes.length)];

  return NextResponse.json({
    joke: randomJoke,
    category,
    topic,
  });
}
