import type { NextRequest } from "next/server";
import { NextResponse } from "next/server";

interface RequestData {
  category: string;
  topic: string;
}

interface AIResponse {
  choices: Array<{
    message: {
      content: string;
    };
  }>;
}

export async function POST(request: NextRequest) {
  const { category, topic } = (await request.json()) as RequestData;

  try {
    const prompt = generatePrompt(category, topic);

    console.log("Making Hack Club AI API call with prompt:", prompt);

    const response = await fetch("https://ai.hackclub.com/chat/completions", {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
      },
      body: JSON.stringify({
        messages: [
          {
            role: "system",
            content:
              "You are a creative joke generator. Your task is to create ORIGINAL, funny jokes from scratch based on the user's prompt. Do NOT use templates or pre-written jokes. Create something genuinely new and creative. Keep jokes family-friendly, under 100 words, and actually funny. Respond with just the joke, no explanations.",
          },
          {
            role: "user",
            content: prompt,
          },
        ],
        max_tokens: 200,
        temperature: 0.9,
      }),
    });

    console.log("Hack Club AI response status:", response.status);

    if (!response.ok) {
      const errorText = await response.text();
      console.error("Hack Club AI error response:", errorText);
      throw new Error(`Hack Club AI error: ${response.status} - ${errorText}`);
    }

    const data = (await response.json()) as AIResponse;
    console.log("Hack Club AI response data:", data);

    const aiJoke = data.choices[0]?.message?.content?.trim();

    if (!aiJoke) {
      throw new Error("No joke generated by AI");
    }

    return NextResponse.json({
      joke: aiJoke,
      category,
      topic,
    });
  } catch (error) {
    console.error("Error generating joke:", error);

    return generateMockJoke(category, topic);
  }
}

function generatePrompt(category: string, topic: string): string {
  const basePrompt =
    category === "people"
      ? `ROAST "${topic}" HARD! Create a savage but funny comedy roast. 
    
Requirements:
- Make it genuinely creative and original
- Keep it clever and witty (not just mean)
- Make it specific to the person's name, job, or characteristics
- Use wordplay, puns, or clever observations
- Maximum 3 lines total
- Make it a proper comedy roast

Just provide the roast directly, no explanations.`
      : `Create a funny, original joke about "${topic}". 
    
Requirements:
- Make it genuinely creative and original
- Keep it family-friendly and appropriate
- Make it specific to the topic provided
- Use wordplay, puns, or clever observations
- Maximum 3 lines total
- Make it actually funny and entertaining

Just provide the joke directly, no explanations.`;

  const categoryContext = {
    people: `ROAST THIS PERSON HARD! Use their name, job, or characteristics to create a savage but funny burn. Maximum 2-3 lines. Be clever, witty, and absolutely roast them. Make it a proper comedy roast.`,
    animals: `Make it about the animal's behavior, characteristics, habits, or natural instincts. Use animal-specific humor.`,
    food: `Use food-related wordplay, cooking scenarios, eating habits, or culinary humor. Make it deliciously funny!`,
    science: `Include scientific concepts, technology, experiments, or educational humor. Make it clever and informative.`,
    school: `Reference learning, education, teachers, students, homework, or school life situations.`,
    work: `Use workplace scenarios, office humor, professional situations, or job-related comedy.`,
    health: `Reference medicine, doctors, nurses, health, wellness, or medical scenarios. Keep it light-hearted.`,
    sports: `Use sports terminology, athletic scenarios, game situations, or competitive humor.`,
    travel: `Reference travel, transportation, vacation scenarios, or journey-related humor.`,
    music: `Use musical terms, instruments, performance scenarios, or rhythm-related humor.`,
    weather: `Reference weather patterns, nature, environmental topics, or seasonal humor.`,
    money: `Use financial terms, business scenarios, economic concepts, or money-related humor. Make it clever about finances!`,
    relationships: `Focus on dating, friendship, relationship dynamics, or social interactions. Keep it clean and fun.`,
    language: `Use wordplay, puns, linguistic humor, or clever language tricks.`,
    time: `Reference time, schedules, calendars, temporal concepts, or time-related humor.`,
    general: `Be creative and original with the topic. Use any style of humor that fits.`,
  };

  const context =
    categoryContext[category as keyof typeof categoryContext] ||
    categoryContext.general;

  return `${basePrompt}\n\nContext: ${context}`;
}

function generateMockJoke(category: string, topic: string) {
  const mockAIJokes = {
    people: [
      `Why did ${topic.split(",")[0]} go to the doctor? Because they needed a check-up!`,
      `What do you call ${topic.split(",")[0]}? A real character!`,
      `Why did ${topic.split(",")[0]} cross the road? To get to the punchline!`,
    ],
    animals: [
      `Why did the ${topic} go to the doctor? Because it was feeling a bit under the weather!`,
      `What do you call a ${topic} that sings? A musical ${topic}!`,
      `Why did the ${topic} join a band? Because it had the talent!`,
    ],
    food: [
      `Why did the ${topic} go to the party? Because it was the life of the dish!`,
      `What do you call a ${topic} that's always late? A procrastinating ${topic}!`,
      `Why did the ${topic} go to school? To get smarter!`,
    ],
    science: [
      `Why did the ${topic} go to space? Because it wanted to explore the universe!`,
      `What do you call a ${topic} that's always learning? A curious ${topic}!`,
      `Why did the ${topic} become a scientist? Because it loved experiments!`,
    ],
    general: [
      `Why did the ${topic} go on vacation? Because it needed a break!`,
      `What do you call a ${topic} that's always happy? A cheerful ${topic}!`,
      `Why did the ${topic} go to the gym? To get stronger!`,
    ],
  };

  const categoryJokes =
    mockAIJokes[category as keyof typeof mockAIJokes] || mockAIJokes.general;
  const randomJoke =
    categoryJokes[Math.floor(Math.random() * categoryJokes.length)];

  return NextResponse.json({
    joke: randomJoke,
    category,
    topic,
  });
}
